Title: 
4X Scope 

Meta-Tags:
 Javascript, JS, interview, questions, interview questions,variables,scope,practice

Description:
// var a = 2;
// {
//   var a = 3;
//   {
//     var a = 4;
//     {
//       var a = 5;
//       console.log(a);
//     }
//     console.log(a);
//   }
//   console.log(a);
// }
// console.log(a);


Options:
A)  5
    4
    3
    2

B)  Error

C)  2
    3
    4
    5

D)  2
    2
    2
    2

Solution:
A 